services:
  - type: web
    name: data-cleaning-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scripts.backend:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
    envVars:
      - key: OPENAI_API_KEY
        scope: build,runtime
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: data-cleaning-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        scope: build,runtime
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FASTAPI_URL
        fromService:
          name: data-cleaning-backend
          property: url
